redColorLower : [0, 120, 50]
redColorUpper : [20, 255, 255]
greenColorLower : [50, 220, 0]
greenColorUpper : [60, 255, 255]
yellowColorLower : [10, 220, 0]
yellowColorUpper : [30, 255, 255]

min_radius : 10