redColorLower : [141, 124, 61]
redColorUpper : [180, 255, 125]
greenColorLower : [29, 26, 0]
greenColorUpper : [114, 255, 61]
yellowColorLower : [0, 147, 0]
yellowColorUpper : [31, 255, 255]

min_radius : 60