// Generated by gencpp from file courseworks_answer_w1/signal_msg.msg
// DO NOT EDIT!


#ifndef COURSEWORKS_ANSWER_W1_MESSAGE_SIGNAL_MSG_H
#define COURSEWORKS_ANSWER_W1_MESSAGE_SIGNAL_MSG_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace courseworks_answer_w1
{
template <class ContainerAllocator>
struct signal_msg_
{
  typedef signal_msg_<ContainerAllocator> Type;

  signal_msg_()
    : time_x(0.0)
    , signal_y(0.0)  {
    }
  signal_msg_(const ContainerAllocator& _alloc)
    : time_x(0.0)
    , signal_y(0.0)  {
  (void)_alloc;
    }



   typedef float _time_x_type;
  _time_x_type time_x;

   typedef float _signal_y_type;
  _signal_y_type signal_y;





  typedef boost::shared_ptr< ::courseworks_answer_w1::signal_msg_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::courseworks_answer_w1::signal_msg_<ContainerAllocator> const> ConstPtr;

}; // struct signal_msg_

typedef ::courseworks_answer_w1::signal_msg_<std::allocator<void> > signal_msg;

typedef boost::shared_ptr< ::courseworks_answer_w1::signal_msg > signal_msgPtr;
typedef boost::shared_ptr< ::courseworks_answer_w1::signal_msg const> signal_msgConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::courseworks_answer_w1::signal_msg_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::courseworks_answer_w1::signal_msg_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::courseworks_answer_w1::signal_msg_<ContainerAllocator1> & lhs, const ::courseworks_answer_w1::signal_msg_<ContainerAllocator2> & rhs)
{
  return lhs.time_x == rhs.time_x &&
    lhs.signal_y == rhs.signal_y;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::courseworks_answer_w1::signal_msg_<ContainerAllocator1> & lhs, const ::courseworks_answer_w1::signal_msg_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace courseworks_answer_w1

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::courseworks_answer_w1::signal_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::courseworks_answer_w1::signal_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::courseworks_answer_w1::signal_msg_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::courseworks_answer_w1::signal_msg_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::courseworks_answer_w1::signal_msg_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::courseworks_answer_w1::signal_msg_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::courseworks_answer_w1::signal_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7a11f0834f5ad70ec78337929f76544a";
  }

  static const char* value(const ::courseworks_answer_w1::signal_msg_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7a11f0834f5ad70eULL;
  static const uint64_t static_value2 = 0xc78337929f76544aULL;
};

template<class ContainerAllocator>
struct DataType< ::courseworks_answer_w1::signal_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "courseworks_answer_w1/signal_msg";
  }

  static const char* value(const ::courseworks_answer_w1::signal_msg_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::courseworks_answer_w1::signal_msg_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 time_x\n"
"float32 signal_y\n"
;
  }

  static const char* value(const ::courseworks_answer_w1::signal_msg_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::courseworks_answer_w1::signal_msg_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.time_x);
      stream.next(m.signal_y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct signal_msg_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::courseworks_answer_w1::signal_msg_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::courseworks_answer_w1::signal_msg_<ContainerAllocator>& v)
  {
    s << indent << "time_x: ";
    Printer<float>::stream(s, indent + "  ", v.time_x);
    s << indent << "signal_y: ";
    Printer<float>::stream(s, indent + "  ", v.signal_y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // COURSEWORKS_ANSWER_W1_MESSAGE_SIGNAL_MSG_H
